environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x" # currently 3.4.3
      PYTHON_ARCH: "32"
  access_token:
    secure: dUqKkqxYQp2WBhKWr7dtWRM4TA7/YFXCL8TC/KwVxif6Mie71tJtyQ38zQYoiojj

branches:
  only:
    - trigger

install:
  # Download setup scripts and unzip
  - ps: "wget https://github.com/cloudify-cosmo/appveyor-utils/archive/master.zip -OutFile ./master.zip"
  - "7z e master.zip */appveyor/* -oappveyor"

  # Install Python (from the official .msi of http://python.org) and pip when
  # not already installed.
  - "powershell ./appveyor/install.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  
  # Install the patacrep compilation toolchain
  - "pip install https://github.com/patacrep/patacrep/archive/master.zip"

  # Git setup
  - "git checkout master"
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "team@appveyor.com"
  - git config --global user.name "AppVeyor"
  - git config --global push.default simple

  # Download miktex portable (if not cached)
  - ps: "If (!(Test-Path miktex-portable.exe)){wget http://mirrors.ctan.org/systems/win32/miktex/setup/miktex-portable.exe -OutFile ./miktex-portable.exe}"

  # Unzip miktex portable
  - "7z x miktex-portable.exe * -aot -omiktex > nul"

  # Let the binaries be directly callable
  - cmd: set PATH=%PATH%;C:\projects\patadata-pdf\miktex\miktex\bin

  # Update fonts
  - cmd: luaotfload-tool.exe --update

  # Manually install required texlive packages
  - ps: "wget https://raw.githubusercontent.com/patacrep/patacrep/master/texlive_packages.txt -OutFile ./texlive_packages.txt"
  - cmd: mpm.exe --install-some texlive_packages.txt

  # Retrieve patadata
  - ps: "wget https://github.com/patacrep/patadata/archive/yaml.zip -OutFile ./patadata.zip"
  - "7z x patadata.zip * -aot -opatadata > nul"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  # Compile the songbooks
  - "songbook patadata\\patadata-yaml\\books\\songbook -v"
  - "dir patadata\\patadata-yaml\\books"
  - "dir ."
  - "git add songbook.pdf"
  - "git commit -m \"Automatic build\""
  - "git push origin"

# Don't cache Miktex Portable file
#cache:
#- C:\projects\patadata-pdf\miktex-portable.exe
